Repository Hooked-On/Field_website, pull requests merged in 2024-02, with the labels that each got.

#8 [Camp page]: refactoring
  .eslintrc.cjs
  .eslintrc.json
  package-lock.json
  package.json
  src/App.jsx
  src/GlobalStyle.jsx
  src/assets/CampBackground.jpg
  src/assets/camp1.png
  src/assets/camp2.png
  src/assets/camp3.png
  src/assets/transfer-down-light.svg
  src/components/Camp/CampImageSection.jsx
  src/components/Camp/CampIntroSection.jsx
  src/components/Camp/CampMainSection.jsx
  src/index.css
  src/pages/CampPage.jsx
Labels: refactor

#9 Main page
  .eslintrc.json
  package-lock.json
  package.json
  public/fieldIntro1.png
  public/fieldLogo.png
  public/scrollDown.png
  src/App.jsx
  src/assets/fieldIntro2.png
  src/assets/fieldIntro3.png
  src/components/AnimationExample.jsx
  src/components/ThreeDCube.jsx
  src/main.jsx
  src/pages/MainPage.jsx
Labels: refactor

#10 [ContactPage] : refactoring
  public/down.png
  src/App.jsx
  src/components/contact/ContactForm.jsx
  src/pages/ContactPage.jsx
Labels: refactor

#18 [font]: font bug해결
  .gitignore
  src/App.jsx
  src/index.css
  src/layout/Header.jsx
  src/pages/RecruitPage.jsx
Labels: bug, urgent, chore

#21 [mainPage, aboutPage] : DB 통신, 마크업 및 스타일링 완료
  public/profile1.png
  src/App.jsx
  src/components/About/Card.jsx
  src/components/About/DepartmentIntro.jsx
  src/components/AnimationExample.jsx
  src/components/CategoryButton.jsx
  src/pages/AboutPage.jsx
  src/pages/MainPage.jsx
Labels: feat, UI

#22 [Camp page] 백통신
  .gitignore
  package-lock.json
  package.json
  src/assets/Group 19.png
  src/assets/modalClose.png
  src/assets/modalIcon.png
  src/components/Button.jsx
  src/components/Camp/CampImageSection.jsx
  src/components/Camp/CampIntroSection.jsx
  src/components/Camp/CampMainSection.jsx
  src/components/Camp/CampTopicSection.jsx
  src/components/Modal.jsx
  src/components/ModalSection.jsx
  src/index.css
  src/lib/Apiservice.jsx
  src/main.jsx
  src/pages/CampPage.jsx
  src/redux/campYearSlice.jsx
  src/redux/store/store.jsx
Labels: feat, UI

#23 [layout, contact, recruit] : 초기 구현
  index.html
  public/Chat_alt_3.png
  public/Check.png
  public/Ellipse 47.png
  public/Expand_down.png
  public/Instagram.png
  public/KakaoTalk.png
  public/Message.png
  public/Phone.png
  public/Youtube.png
  public/happy.png
  public/right_up_arrow.png
  src/components/Recruit/Content.jsx
  src/components/Recruit/Department.jsx
  src/components/Recruit/Qustion.jsx
  src/components/contact/ContactForm.jsx
  src/components/contact/ContactModal.jsx
  src/layout/Footer/Footer.jsx
  src/layout/Header/Header.jsx
  src/layout/Header/MenuBurgur.jsx
  src/layout/Header/MenuContent.jsx
  src/layout/Layout.jsx
  src/pages/ContactPage.jsx
  src/pages/RecruitPage.jsx
Labels: feat, UI

#26 [Recruit, layout] : 구현
  public/KakaoTalk.png
  public/MessageWhite.png
  src/App.jsx
  src/components/Recruit/Content.jsx
  src/components/Recruit/Department.jsx
  src/components/Recruit/Qustion.jsx
  src/fonts/goblin_one.css
  src/fonts/goblin_one.eot
  src/fonts/goblin_one.svg
  src/fonts/goblin_one.ttf
  src/fonts/goblin_one.woff
  src/fonts/goblin_one.woff2
  src/index.css
  src/layout/Footer/Footer.jsx
  src/layout/Header/Header.jsx
  src/layout/Header/MenuContent.jsx
  src/lib/Apiservice.jsx
  src/pages/RecruitPage.jsx
Labels: feat, UI

#27 [Contact, Recruit, layout] : 구현
  src/components/Recruit/Content.jsx
  src/components/Recruit/Department.jsx
  src/components/Recruit/Qustion.jsx
  src/components/contact/ContactForm.jsx
  src/layout/Footer/Footer.jsx
  src/layout/Header/Header.jsx
  src/layout/Header/MenuBurgur.jsx
  src/layout/Header/MenuContent.jsx
  src/lib/Apiservice.jsx
  src/pages/ContactPage.jsx
  src/pages/RecruitPage.jsx
Labels: bug, feat, UI

#28 [mainPage, aboutPage] 완성
  public/ActivityCamp.png
  public/ActivityInterview.png
  public/ActivityIntro.png
  public/ActivityLt.png
  public/ActivitySeminar.png
  public/ActivitySupport.png
  public/ActivityYoutube.png
  public/FieldIntro2.png
  public/FieldIntro3.png
  src/App.jsx
  src/components/About/DepartmentIntro.jsx
  src/components/Main/ActivityIntro.jsx
  src/components/Main/FieldIntro.jsx
  src/index.css
  src/layout/Footer/Footer.jsx
  src/layout/Header/Header.jsx
  src/lib/Apiservice.jsx
  src/pages/AboutPage.jsx
  src/pages/MainPage.jsx
Labels: feat, UI

#29 [News page]: 페이지 구성 및 백통신
  src/App.jsx
  src/assets/fileIcon.png
  src/components/Button.jsx
  src/components/Camp/CampImageSection.jsx
  src/components/Camp/CampIntroSection.jsx
  src/components/Camp/CampMainSection.jsx
  src/components/Camp/CampTopicSection.jsx
  src/components/CategoryButton.jsx
  src/components/LoadingSpinner.jsx
  src/components/Modal.jsx
  src/components/ModalSection.jsx
  src/components/News/NewsPagination.jsx
  src/index.css
  src/layout/Footer/Footer.jsx
  src/layout/Header/MenuContent.jsx
  src/lib/Apiservice.jsx
  src/pages/NewsDetailPage.jsx
  src/pages/NewsPage.jsx
  src/redux/campYearSlice.jsx
  src/redux/modalTitleSlice.jsx
  src/redux/store/store.jsx
Labels: feat, UI

#32 [Time line] : TimeLine 구현
  src/App.jsx
  src/components/Recruit/Content.jsx
  src/components/Recruit/Department.jsx
  src/components/TimeLine.jsx
  src/components/contact/ContactForm.jsx
  src/components/contact/ContactModal.jsx
  src/layout/Footer/Footer.jsx
  src/layout/Header/Header.jsx
  src/pages/RecruitPage.jsx
Labels: feat

#34 [News page, layout]: 백통신 오류 수정, 해더 버그 수정
  .prettierrc.json
  public/Refund_back.png
  src/components/Button.jsx
  src/components/Camp/CampImageSection.jsx
  src/components/Camp/CampIntroSection.jsx
  src/components/Camp/CampTopicSection.jsx
  src/components/CategoryButton.jsx
  src/components/Modal.jsx
  src/components/ModalSection.jsx
  src/components/News/NewsPagination.jsx
  src/layout/Header/Header.jsx
  src/layout/Header/MenuContent.jsx
  src/pages/MainPage.jsx
  src/pages/NewsDetailPage.jsx
  src/pages/NewsPage.jsx
  src/redux/campTitleSlice.jsx
  src/redux/monthFieldSlice.jsx
  src/redux/store/store.jsx
Labels: bug

#35 [mainPage] localStorage 사용
  package-lock.json
  package.json
  src/components/About/DepartmentIntro.jsx
  src/components/AnimationExample.jsx
  src/components/Main/ActivityIntro.jsx
  src/components/Main/FieldIntro.jsx
  src/components/Modal.jsx
  src/components/News/NewsPagination.jsx
  src/main.jsx
  src/pages/AboutPage.jsx
  src/pages/MainPage.jsx
  src/pages/NewsPage.jsx
Labels: feat, UI

#37 [Time line] : TIme line 리팩토링
  src/components/TimeLine.jsx
Labels: refactor

#39 [Layout] : Sidebar, Notfound 구현
  public/InstagramIcon.png
  public/KakaoTalkIcon.png
  public/YoutubeIcon.png
  src/App.jsx
  src/layout/Layout.jsx
  src/layout/component/Sidebar.jsx
  src/pages/NotFound.jsx
Labels: feat

#40 [Recruit page] : 코드 리팩토링
  src/components/Recruit/Content.jsx
  src/components/Recruit/Department.jsx
  src/lib/Apiservice.jsx
  src/pages/RecruitPage.jsx
Labels: refactor

#42 [Refactoring]: 코드 리팩토링
  src/components/Camp/CampImageSection.jsx
  src/components/Camp/CampIntroSection.jsx
  src/components/Camp/CampMainSection.jsx
  src/components/Camp/CampTimeLine.jsx
  src/components/Camp/CampTopicSection.jsx
  src/components/LoadingSpinner.jsx
  src/components/Main/TitleSection.jsx
  src/components/Modal.jsx
  src/components/ModalSection.jsx
  src/components/News/NewsPagination.jsx
  src/components/ScrollToTop.jsx
  src/components/contact/ContactForm.jsx
  src/layout/Footer/Footer.jsx
  src/layout/Header/MenuContent.jsx
  src/main.jsx
  src/pages/CampPage.jsx
  src/pages/ContactPage.jsx
  src/pages/MainPage.jsx
  src/pages/NewsDetailPage.jsx
  src/pages/NewsPage.jsx
  src/redux/campTitleSlice.jsx
  src/redux/monthFieldSlice.jsx
  src/redux/store/store.jsx
Labels: refactor, UI

#43 [Refactoring] 코드 리팩토링
  src/pages/NotFound.jsx
Labels: refactor

#44 [Refactoring] 코드 리팩토링
  public/fieldIntro1.png
Labels: refactor
