Repository Hooked-On/Field_website, pull requests merged in 2024-03, with the labels that each got.

#50 [Recruit page] : 변경사항 및 피드백 반영
  src/GlobalStyle.jsx
  src/components/Recruit/Content.jsx
  src/components/Recruit/Department.jsx
  src/components/Recruit/Notification.jsx
  src/components/Recruit/Qustion.jsx
  src/components/Recruit/UI/ContentWrapper.jsx
  src/components/TimeLine.jsx
  src/pages/RecruitPage.jsx
Labels: UI

#51 [ContactPage]: 변경사항 및 피드백 반영
  src/components/contact/ContactForm.jsx
  src/components/contact/ContactModal.jsx
Labels: UI

#53 [mainPage, aboutPage] : 피드백 반영
  src/components/About/DepartmentIntro.jsx
  src/components/Main/IntroSection.jsx
  src/components/Main/ReviewSection.jsx
  src/components/Main/TitleSection.jsx
  src/components/TextGenerator.jsx
  src/pages/AboutPage.jsx
  src/pages/MainPage.jsx
Labels: refactor

#56 [Recruit page] : 텍스트 위치 조정 및 내용 변경
  src/components/Recruit/Content.jsx
  src/components/Recruit/Department.jsx
Labels: UI

#58 [Refactoring]
  package-lock.json
  package.json
  public/Expand_down_white.png
  src/App.jsx
  src/components/Camp/CampIntroSection.jsx
  src/components/Camp/CampMainSection.jsx
  src/components/Camp/CampTimeLine.jsx
  src/components/Camp/CampTopicSection.jsx
  src/components/CategoryButton.jsx
  src/components/Dropdown.jsx
  src/components/Modal.jsx
  src/components/News/NewsPagination.jsx
  src/lib/Apiservice.jsx
  src/pages/CampPage.jsx
  src/pages/NewsPage.jsx
  src/pages/_NewsPage.jsx
  src/redux/monthFieldSlice.jsx
  src/theme.jsx
  vite.config.js
Labels: refactor

#59 [NewPage] 필터 구현 (미완)
  src/components/Main/IntroSection.jsx
  src/components/News/NewsPagination.jsx
  src/pages/NewsPage.jsx
Labels: feat

#60 [NewsPage]: 필터 오류 수정(미완)
  src/components/News/NewsPagination.jsx
  src/lib/Apiservice.jsx
  src/pages/CampPage.jsx
  src/pages/NewsPage.jsx
  src/pages/asd.jsx
Labels: bug

#61 [:bug] News 디테일 페이지 뒤로가기 버그 수정
  src/components/Recruit/Department.jsx
  src/pages/NewsPage.jsx
Labels: feat

#64 [Recruit page] : 로컬스토리지 기한 설정, NotFound 페이지
  public/Notice.png
  src/components/Recruit/Content.jsx
  src/pages/NotFound.jsx
Labels: feat, UI

#65 [Contactpage] : 모달창 리팩토링
  src/components/contact/ContactForm.jsx
  src/components/contact/ContactModal.jsx
Labels: UI

#63 [mainPage, aboutPage]: 피드백 반영
  src/components/About/ManagerIntro.jsx
  src/components/About/TimelineSection.jsx
  src/components/Main/FieldIntro.jsx
  src/components/Main/ReviewSection.jsx
  src/components/TimeLine.jsx
  src/lib/Apiservice.jsx
Labels: feat

#70 [contact,recruit,layout]: 최종 피드백 수정
  public/Expand_down.png
  public/InstagramIcon.jpg
  public/InstagramIcon.png
  public/KakaoTalkIcon.png
  public/YoutubeIcon.png
  public/down_arrow.png
  src/components/Recruit/Content.jsx
  src/components/Recruit/Qustion.jsx
  src/components/contact/ContactForm.jsx
  src/layout/component/Sidebar.jsx
Labels: bug, UI

#72 [Refactoring]
  as
  public/camp1.png
  public/camp2.png
  public/camp3.png
  public/camp4.jpg
  public/fileIcon.png
  public/transfer-down-light.svg
  src/assets/CampBackground.jpg
  src/assets/Group 19.png
  src/assets/camp1.png
  src/assets/camp2.png
  src/assets/camp3.png
  src/assets/modalClose.png
  src/assets/modalIcon.png
  src/components/About/DepartmentIntro.jsx
  src/components/About/TitleSection.jsx
  src/components/Button.jsx
  src/components/Camp/CampImageSection.jsx
  src/components/Camp/CampIntroSection.jsx
  src/components/Camp/CampMainSection.jsx
  src/components/Camp/CampTimeLine.jsx
  src/components/Camp/CampTopicSection.jsx
  src/components/Dropdown.jsx
  src/components/Main/ActivitySection.jsx
  src/components/Main/FieldIntro.jsx
  src/components/Main/IntroSection.jsx
  src/components/Main/ReviewSection.jsx
  src/components/Main/TitleSection.jsx
  src/components/News/NewsPagination.jsx
  src/components/TextGenerator.jsx
  src/lib/Apiservice.jsx
  src/pages/CampPage.jsx
  src/pages/NewsDetailPage.jsx
  src/pages/NewsPage.jsx
  src/pages/_NewsPage.jsx
  src/pages/asd.jsx
Labels: refactor

#73 [Contactpage] : 반응형 구현
  src/GlobalStyle.jsx
  src/components/contact/ContactForm.jsx
  src/components/contact/ContactInput.jsx
  src/components/contact/ContactModal.jsx
  src/pages/ContactPage.jsx
Labels: UI

#75 [Layout] : 반응형 UI 구현
  src/layout/Footer/Footer.jsx
  src/layout/Header/Header.jsx
  src/layout/Header/MenuContent.jsx
Labels: UI

#76 [Refactoring]: media 쿼리 통한 반응형 웹 구현
  public/camp1.png
  src/components/Button.jsx
  src/components/Camp/CampImageSection.jsx
  src/components/Camp/CampIntroSection.jsx
  src/components/Camp/CampMainSection.jsx
  src/components/Camp/CampTopicSection.jsx
  src/components/News/NewsPagination.jsx
  src/components/TimeLine.jsx
  src/lib/Apiservice.jsx
  src/pages/CampPage.jsx
  src/pages/NewsDetailPage.jsx
  src/pages/NewsPage.jsx
Labels: refactor

#79 [Recruit, layout] : 최종 피드백 반영
  src/App.jsx
  src/components/News/NewsPagination.jsx
  src/components/Recruit/Notification.jsx
  src/layout/Footer/Footer.jsx
  src/layout/Header/MenuContent.jsx
  src/pages/RecruitPage.jsx
Labels: bug, UI

#80 [Refactoring] 피드백 반영
  src/components/Camp/CampImageSection.jsx
  src/components/Camp/CampIntroSection.jsx
  src/components/Camp/CampMainSection.jsx
  src/components/CategoryButton.jsx
  src/components/News/NewsPagination.jsx
  src/components/TimeLine.jsx
  src/pages/NewsDetailPage.jsx
  src/pages/NewsPage.jsx
Labels: refactor

#83 [Deploy]
  .github/workflows/deploy.yaml
  src/components/Camp/CampImageSection.jsx
  src/components/Camp/CampTopicSection.jsx
  src/components/News/NewsPagination.jsx
Labels: help

#90 [Contact, Recruit] : UI field 최종 피드백 반영
  src/components/About/TimelineDetail.jsx
  src/components/Recruit/Content.jsx
  src/components/Recruit/Department.jsx
  src/components/Recruit/Qustion.jsx
  src/components/Recruit/UI/ContentWrapper.jsx
  src/components/TimeLine.jsx
  src/components/contact/ContactForm.jsx
  src/components/contact/ContactInput.jsx
  src/components/contact/ContactModal.jsx
  src/layout/Header/Header.jsx
  src/layout/Header/MenuContent.jsx
  src/layout/component/Sidebar.jsx
  src/pages/NotFound.jsx
Labels: bug, UI

#92 [TimeLine] : 새로운 TimeLine 구현
  src/components/Camp/CampTimeLine.jsx
  src/components/NewTimeLine.jsx
  src/components/NewTimeLineContent.jsx
  src/layout/Header/Header.jsx
Labels: feat

#93 [UI] : Button hover pointer 변경
  src/components/Recruit/Department.jsx
  src/components/Recruit/Qustion.jsx
  src/components/contact/ContactModal.jsx
  src/layout/component/Sidebar.jsx
Labels: UI

#94 [Refactoring] 버튼hover 추가
  src/components/Button.jsx
  src/components/Camp/CampIntroSection.jsx
  src/components/Camp/CampMainSection.jsx
  src/components/Camp/CampTopicSection.jsx
  src/pages/NewsDetailPage.jsx
  src/pages/NewsPage.jsx
Labels: refactor

#99 [refactoring]: 마진변경
  src/components/Camp/CampMainSection.jsx
  src/components/Camp/CampTimeLine.jsx
  src/components/NewTimeLine.jsx
Labels: refactor

#103 [contactPage]: 피드백 반영
  src/components/contact/ContactForm.jsx
  src/components/contact/ContactInput.jsx
Labels: UI

#104 [Refactoring]
  public/camp1.webp
  public/camp2.webp
  public/camp3.webp
  public/camp4.webp
  src/components/Camp/CampMainSection.jsx
  src/pages/CampPage.jsx
  src/pages/NewsDetailPage.jsx
Labels: refactor

#105 [refacoring]
  public/camp1.webp
  public/camp2.webp
  public/camp3.webp
  public/camp4.webp
  src/components/Camp/CampMainSection.jsx
  src/pages/CampPage.jsx
  src/pages/NewsDetailPage.jsx
Labels: refactor

#106 [Refactoring]
  src/components/About/DepartmentIntro.jsx
  src/components/About/TitleSection.jsx
  src/components/NewTimeLineContent.jsx
  src/components/contact/ContactForm.jsx
  src/components/contact/ContactInput.jsx
  src/lib/Apiservice.jsx
  src/pages/MainPage.jsx
  src/pages/NewsDetailPage.jsx
  src/pages/NewsPage.jsx
Labels: refactor

#107 Dev
  src/components/NewTimeLineContent.jsx
  src/lib/Apiservice.jsx
  src/pages/MainPage.jsx
  src/pages/NewsDetailPage.jsx
  src/pages/NewsPage.jsx
Labels: refactor
